apiVersion: v1
kind: Service
metadata:
  name: swagger-service
  labels:
    name: swagger-service
spec:
  selector:
    name: swagger-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer